const concat = require('concat-files');
const path = require('path');

const files = [
// ================ Import ================ 
"src/core/const/Const.j",

"src/import/ARGB.j",
//"src/import/Board.j",
"src/import/Clock.j",
"src/import/Console.j",
"src/import/DataStructure.j",
"src/import/GroupUtils.j",
"src/import/Integer.j",
"src/import/IntegerPool.j",
"src/import/Math.j",
"src/import/NefUnion.j",
"src/import/PlayerState.j",
"src/import/RandomPoint.j",
//"src/import/ReverseAnimation.j",
"src/import/SimError.j",
"src/import/SoundUtils.j",
"src/import/SpellEvent.j",
"src/import/Stack.j",
"src/import/Table.j",
"src/import/TerrainPathability.j",
"src/import/TextTag.j",
"src/import/TimerUtils.j",
"src/import/Vector.j",

// ================ Database ================ 
"src/core/const/MobInit.j",
"src/core/const/ModelInfo.j",
"src/core/const/Sounds.j",
"src/core/const/SpellData.j",

// ================ Core ================ 
"src/core/AggroSystem.j",
//"src/core/AISpell.j",
"src/core/AllianceAIAction.j",
"src/core/BuffSystem.j",
"src/core/CastingBar.j",
"src/core/CombatFacts.j",
"src/core/CreepsAction.j",
"src/core/DamageSystem.j",
"src/core/ForceSight.j",
"src/core/ForcedMovement.j",
"src/core/GameProcess.j",
"src/core/GrantAbilityPoints.j",
"src/core/HeroSelection.j",
// "src/core/InfoBoards.j",
"src/core/InternalCooldown.j",
"src/core/MultipleAbility.j",
"src/core/Patrol.j",
"src/core/PlayerUnitList.j",
"src/core/Projectile.j",
"src/core/Regeneration.j",
"src/core/SpecialProperty.j",
"src/core/SpellReflection.j",
"src/core/StunUtils.j",
"src/core/UnitAbilityCD.j",
"src/core/UnitProperty.j",
"src/core/WELA.j",
"src/core/ZAMCore.j",

// ================ Hero Abilities ================
"src/hero/BloodElfDefender/ShieldBlock.j",
"src/hero/BloodElfDefender/SunField.j",
"src/hero/BloodElfDefender/ArcaneShock.j",
"src/hero/BloodElfDefender/Discord.j",
"src/hero/BloodElfDefender/ShieldOfSindorei.j",
//"src/hero/BloodElfDefender/DefensiveAura.j",

"src/hero/ClawDruid/ClawDruidGlobal.j",
"src/hero/ClawDruid/Lacerate.j",
"src/hero/ClawDruid/SavageRoar.j",
"src/hero/ClawDruid/ForestCure.j",
"src/hero/ClawDruid/NaturalReflex.j",
"src/hero/ClawDruid/SurvivalInstincts.j",
//"src/hero/ClawDruid/BearForm.j",
//"src/hero/ClawDruid/Mangle.j",
//"src/hero/ClawDruid/Gnaw.j",
//"src/hero/ClawDruid/BeastAura.j",

"src/hero/Priest/Heal.j",
"src/hero/Priest/PrayerOfHealing.j",
"src/hero/Priest/Shield.j",
"src/hero/Priest/PrayerOfMending.j",
"src/hero/Priest/Dispel.j",
//"src/hero/Priest/FortitudeAura.j",
//"src/hero/Priest/PrayerOfHealing_deprecated.j",
//"src/hero/Priest/Heal_deprecated.j",

"src/hero/Paladin/PaladinGlobal.j",
"src/hero/Paladin/FlashOfLight.j",
"src/hero/Paladin/HolyLight.j",
"src/hero/Paladin/HolyShock.j",
"src/hero/Paladin/DivineFavor.j",
"src/hero/Paladin/BeaconOfLight.j",

"src/hero/KeeperOfGrove/KeeperOfGroveGlobal.j",
"src/hero/KeeperOfGrove/LifeBloom.j",
"src/hero/KeeperOfGrove/Rejuvenation.j",
"src/hero/KeeperOfGrove/Regrowth.j",
"src/hero/KeeperOfGrove/SwiftMend.j",
"src/hero/KeeperOfGrove/Tranquility.j",

"src/hero/BladeMaster/BladeMasterGlobal.j",
"src/hero/BladeMaster/HeroicStrike.j",
"src/hero/BladeMaster/Rend.j",
"src/hero/BladeMaster/Overpower.j",
"src/hero/BladeMaster/MortalStrike.j",
"src/hero/BladeMaster/Execute.j",
//"src/hero/BladeMaster/ValourAura.j",

"src/hero/Rogue/RogueGlobal.j",
"src/hero/Rogue/SinisterStrike.j",
"src/hero/Rogue/Eviscerate.j",
"src/hero/Rogue/Assault.j",
"src/hero/Rogue/BladeFlurry.j",
"src/hero/Rogue/Stealth.j",
"src/hero/Rogue/Garrote.j",
"src/hero/Rogue/Ambush.j",

"src/hero/DarkRanger/DarkRangerGlobal.j",
"src/hero/DarkRanger/DarkArrow.j",
"src/hero/DarkRanger/Concerntration.j",
"src/hero/DarkRanger/FreezingTrap.j",
"src/hero/DarkRanger/PowerOfAbomination.j",
"src/hero/DarkRanger/DeathPact.j",
"src/hero/DarkRanger/SummonGhoul.j",
"src/hero/DarkRanger/LifeLeech.j",
"src/hero/DarkRanger/EvilImbue.j",

"src/hero/FrostMage/FrostMageGlobal.j",
"src/hero/FrostMage/FrostBolt.j",
"src/hero/FrostMage/Blizzard.j",
"src/hero/FrostMage/FrostNova.j",
"src/hero/FrostMage/Polymorph.j",
"src/hero/FrostMage/SpellTransfer.j",
//"src/hero/FrostMage/DalaranAura.j",

"src/hero/Heretic/HeathenGlobal.j",
"src/hero/Heretic/Pain.j",
"src/hero/Heretic/MarrowSqueeze.j",
"src/hero/Heretic/MindFlay.j",
"src/hero/Heretic/Death.j",
"src/hero/Heretic/Terror.j",

"src/hero/EarthBinder/EarthBinderGlobal.j",
"src/hero/EarthBinder/StormLash.j",
"src/hero/EarthBinder/EarthShock.j",
"src/hero/EarthBinder/Purge.j",
"src/hero/EarthBinder/EnchantingTotem.j",
"src/hero/EarthBinder/Ascendance.j",
//"src/hero/EarthBinder/StormStrike.j",
//"src/hero/EarthBinder/Charge.j",
//"src/hero/EarthBinder/WindGrace.j",

// ================ Boss ================
"src/boss/Frenzy.j",
"src/boss/Rage.j",

"src/boss/ArchTinker/ClusterRockets.j",
"src/boss/ArchTinker/GripOfStaticElectricity.j",
"src/boss/ArchTinker/LaserBeam.j",
"src/boss/ArchTinker/LightningShield.j",
"src/boss/ArchTinker/PocketFactory.j",
"src/boss/ArchTinker/PulseBomb.j",
"src/boss/ArchTinker/SelfDestruct.j",
"src/boss/ArchTinker/SummonClockworkGoblin.j",

"src/boss/NagaSeaWitch/ForkedLightning.j",
"src/boss/NagaSeaWitch/StrongBreeze.j",
"src/boss/NagaSeaWitch/SummonSerpents.j",
"src/boss/NagaSeaWitch/ThunderStorm.j",

"src/boss/TideBaron/TideBaronGlobal.j",
"src/boss/TideBaron/TideBaronMorph.j",
"src/boss/TideBaron/AlkalineWater.j",
"src/boss/TideBaron/Lancinate.j",
"src/boss/TideBaron/RaspyRoar.j",
"src/boss/TideBaron/TearUp.j",
"src/boss/TideBaron/Tide.j",

"src/boss/Warlock/WarlockGlobal.j",
"src/boss/Warlock/FireBomb.j",
"src/boss/Warlock/FlameThrow.j",
"src/boss/Warlock/SummonLavaSpawn.j",
"src/boss/Warlock/FrenzyWarlock.j",

"src/boss/AbyssArchon/AbyssArchonGlobal.j",
"src/boss/AbyssArchon/Impale.j",
"src/boss/AbyssArchon/SummonPoisonousCrawler.j",
"src/boss/AbyssArchon/LifeSiphon.j",
"src/boss/AbyssArchon/SummonAbomination.j",
"src/boss/AbyssArchon/SummonWraith.j",

"src/boss/HexLord/HexLordGlobal.j",
"src/boss/HexLord/SpiritBolt.j",
"src/boss/HexLord/SpiritHarvest.j",
"src/boss/HexLord/SunfireStormHex.j",
"src/boss/HexLord/ShieldOfSindoreiHex.j",
"src/boss/HexLord/SavageRoarHex.j",
"src/boss/HexLord/NaturalReflexHex.j",
"src/boss/HexLord/HealHex.j",
"src/boss/HexLord/ShieldHex.j",
"src/boss/HexLord/LifeBloomHex.j",
"src/boss/HexLord/TranquilityHex.j",
"src/boss/HexLord/HolyLightHex.j",
"src/boss/HexLord/HolyShockHex.j",
"src/boss/HexLord/FrostBoltHex.j",
"src/boss/HexLord/PolymorphHex.j",
"src/boss/HexLord/PainHex.j",
"src/boss/HexLord/TerrorHex.j",
"src/boss/HexLord/LightningTotemHex.j",
"src/boss/HexLord/ChargeHex.j",
"src/boss/HexLord/MortalStrikeHex.j",
"src/boss/HexLord/OverpowerHex.j",
"src/boss/HexLord/DarkArrowHex.j",
"src/boss/HexLord/FreezingTrapHex.j",
"src/boss/HexLord/StealthHex.j",
"src/boss/HexLord/BladeFlurryHex.j",

// ================ Creeps ================
// Area 0-2
"src/creep/Sting.j",
"src/creep/LightningBolt.j",
"src/creep/FrostShock.j",
"src/creep/ChainHealing.j",
"src/creep/HealingWard.j",
"src/creep/ProtectionWard.j",
"src/creep/ChargedBreath.j",
"src/creep/ManaLeech.j",
"src/creep/NagaFrenzy.j",
"src/creep/ArmorCrushing.j",
"src/creep/ThunderClap.j",
"src/creep/RageRoar.j",
// Area 3
"src/creep/UnholyFrenzy.j",
"src/creep/ChaosLeap.j",
"src/creep/WarStomp.j",
"src/creep/BattleCommand.j",
"src/creep/BlazingHaste.j",
"src/creep/FireBall.j",
"src/creep/FlameShock.j",
// Area 4
"src/creep/Parasite.j",
"src/creep/Gnaw.j",
"src/creep/ReflectionAura.j",
"src/creep/ManaTap.j",
"src/creep/FrostGrave.j",
"src/creep/DeathAndDecay.j",
// Area 5
"src/creep/NetherBolt.j",
"src/creep/ShadowShift.j",
"src/creep/ManaBurn.j",
"src/creep/ShadowSpike.j",
"src/creep/MarkOfAgony.j",
"src/creep/NetherImplosion.j",
"src/creep/NetherBreath.j",
"src/creep/NetherSlow.j",
"src/creep/Meteor.j",
"src/creep/Burning.j",
// Area 6
"src/creep/CrushingBlow.j",
"src/creep/ForestStomp.j",
"src/creep/Zeal.j",
"src/creep/CorpseRain.j",
"src/creep/VoodooDoll.j",
"src/creep/SlamStrike.j",
"src/creep/Vomit.j",
"src/creep/PoisonDart.j",
"src/creep/GrimTotem.j",
"src/creep/ViciousStrike.j",
"src/creep/FilthyLand.j",

// ================ Items ================
"src/item/ItemType.j",
"src/item/ItemAttributes.j",
"src/item/Loot.j",

"src/item/ConsumableScroll/AransCounterSpellScroll.j",
"src/item/ConsumableScroll/ArmageddonScroll.j",
"src/item/ConsumableScroll/BansheeScroll.j",
"src/item/ConsumableScroll/CorruptionScroll.j",
"src/item/ConsumableScroll/DefendScroll.j",
"src/item/ConsumableScroll/FrenzyScroll.j",
"src/item/ConsumableScroll/HealScroll.j",
"src/item/ConsumableScroll/ManaScroll.j",
"src/item/ConsumableScroll/MassDispelScroll.j",
"src/item/ConsumableScroll/MassTeleportScroll.j",
"src/item/ConsumableScroll/RoarScroll.j",
"src/item/ConsumableScroll/SanctuaryScroll.j",
"src/item/ConsumableScroll/SlayerScroll.j",
"src/item/ConsumableScroll/SpeedScroll.j",
"src/item/ConsumableScroll/SpellReflectionScroll.j",
"src/item/ConsumableScroll/WeakenCurseScroll.j",

"src/item/ConsumablePotion/AcutePotion.j",
"src/item/ConsumablePotion/AgilityPotion.j",
"src/item/ConsumablePotion/AngryCastPotion.j",
"src/item/ConsumablePotion/ArcanePotion.j",
"src/item/ConsumablePotion/ArchMagePotion.j",
"src/item/ConsumablePotion/BigLifePotion.j",
"src/item/ConsumablePotion/CombatMasterPotion.j",
"src/item/ConsumablePotion/DexterityPotion.j",
"src/item/ConsumablePotion/DodgePotion.j",
"src/item/ConsumablePotion/EmperorsNewPotion.j",
"src/item/ConsumablePotion/FortressPotion.j",
"src/item/ConsumablePotion/InvulPotion.j",
"src/item/ConsumablePotion/LeechPotion.j",
"src/item/ConsumablePotion/LifePotion.j",
"src/item/ConsumablePotion/LifeRegenPotion.j",
"src/item/ConsumablePotion/ManaPotion.j",
"src/item/ConsumablePotion/ManaRegenPotion.j",
"src/item/ConsumablePotion/ManaSourcePotion.j",
"src/item/ConsumablePotion/ShieldPotion.j",
"src/item/ConsumablePotion/SmallInvulPotion.j",
"src/item/ConsumablePotion/SpellMasteryPotion.j",
"src/item/ConsumablePotion/SpellPiercePotion.j",
"src/item/ConsumablePotion/SpellPowerPotion.j",
"src/item/ConsumablePotion/StoneSkinPotion.j",
"src/item/ConsumablePotion/TranquilityPotion.j",
"src/item/ConsumablePotion/TransferPotion.j",
"src/item/ConsumablePotion/UnstablePotion.j",

"src/item/ConsumableCharm/CharmOfChainLightning.j",
"src/item/ConsumableCharm/CharmOfDeathFinger.j",
"src/item/ConsumableCharm/CharmOfDispel.j",
"src/item/ConsumableCharm/CharmOfHealingWard.j",
"src/item/ConsumableCharm/CharmOfInnerFire.j",
"src/item/ConsumableCharm/CharmOfSimpleHeal.j",
"src/item/ConsumableCharm/CharmOfSiphonLife.j",
"src/item/ConsumableCharm/DemonicRune.j",
"src/item/ConsumableCharm/StrangeWand.j",

"src/item/Common/BootsOfSlow.j",
"src/item/Common/HelmOfValour.j",
"src/item/Common/HoodOfCunning.j",
"src/item/Common/MedalionOfCourage.j",

"src/item/Uncommon/RandomPrefixed.j",
"src/item/Uncommon/CruelColossusBladeOfQuickness.j",
"src/item/Uncommon/HealthStone.j",
"src/item/Uncommon/IconOfTheUnglazedCrescent.j",
"src/item/Uncommon/ManaStone.j",
"src/item/Uncommon/MoroesLuckyGear.j",
"src/item/Uncommon/RomulosExpiredPoison.j",
"src/item/Uncommon/RunedBracers.j",

"src/item/Rare/AransSoothingAgate.j",
"src/item/Rare/BulwarkOfTheAmaniEmpire.j",
"src/item/Rare/CoreHoundTooth.j",
"src/item/Rare/CursedCuirass.j",
"src/item/Rare/Drum.j",
"src/item/Rare/GoblinRocketBootsLimitedEdition.j",
"src/item/Rare/GoreHowl.j",
"src/item/Rare/HexShrunkenHead.j",
"src/item/Rare/LionHorn.j",
"src/item/Rare/PureArcane.j",
"src/item/Rare/SignetOfTheLastDefender.j",
"src/item/Rare/StaffOfTheShadowFlame.j",
"src/item/Rare/The21Ring.j",
"src/item/Rare/TidalLoop.j",
"src/item/Rare/TrollBane.j",
"src/item/Rare/Viskag.j",

"src/item/ClassSpec/Anathema.j",
"src/item/ClassSpec/Benediction.j",
"src/item/ClassSpec/DaggerOfAssassination.j",
"src/item/ClassSpec/HornOfCenarius.j",
"src/item/ClassSpec/LightsJustice.j",
"src/item/ClassSpec/OrbOfTheSindorei.j",
"src/item/ClassSpec/OrcCaptureFlag.j",
"src/item/ClassSpec/RageWinterchillsPhylactery.j",
"src/item/ClassSpec/RareShimmerWeed.j",
"src/item/ClassSpec/ReforgedBadgeOfTenacity.j",
"src/item/ClassSpec/RhokDelar.j",

"src/item/Relic/BreathOfTheDying.j",
"src/item/Relic/CallToArms.j",
"src/item/Relic/CthunsDerangement.j",
"src/item/Relic/Enigma.j",
"src/item/Relic/Infinity.j",
"src/item/Relic/Insight.j",
"src/item/Relic/TyraelsMight.j",
"src/item/Relic/VoodooVial.j",
"src/item/Relic/WindForce.j",
"src/item/Relic/WoeStave.j",

//"src/item/LegendarySetArthasCorruption/ArthassCorruption.j",
//"src/item/LegendarySetArthasCorruption/DeterminationOfVengeance.j",
//"src/item/LegendarySetArthasCorruption/StratholmeTragedy.j",
//"src/item/LegendarySetArthasCorruption/Patricide.j",
//"src/item/LegendarySetArthasCorruption/FrostMourne.j",

// ================ Items ================
"src/test/Command.j",
"src/test/DebugExporter.j",
"src/test/HealTester.j"
];

if (process.env.TESH_HOME == undefined) {
    console.log('TESH_HOME is not defined');
} else {
    const output = path.join(process.env.TESH_HOME, 'templates', 'standard.txt');
    concat(files, output, function(err) {
        if (err) {
            console.log('Build failed: ' + err);
        } else {
            console.log('Build finished: ' + output);
        }
    });
}
